In [1]:
import _blob

In [2]:
a = _blob.Blob()

In [3]:
a.reshape(1,2)

In [4]:
a.shape_string

'1 2 (2)'

In [5]:
_blob.mode()

'CPU'

In [10]:
b = _blob.Blob()
b.reshape_like(a)
shape = b.shape
for i in shape:
    print(i)

1
2


In [11]:
shape = a.shape
for i in shape:
    print(i)

1
2


In [12]:
shape.tostring()

AttributeError: 'vector<int>' object has no attribute 'tostring'

In [13]:
a.count

2

In [14]:
a.data_ptr

189072784

In [15]:
import numpy as np

In [16]:
a.data

array([[ 0.,  0.]], dtype=float32)

In [17]:
data = [[1,2]]

In [18]:
np_data = np.array(data)

In [19]:
np_data.astype(np.float32)

array([[ 1.,  2.]], dtype=float32)

In [20]:
np_data.shape

(1, 2)

In [21]:
a.data[...] = np_data/2.0 

In [22]:
a.data

array([[ 0.5,  1. ]], dtype=float32)

In [23]:
a.diff

array([[ 0.,  0.]], dtype=float32)